// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "e-volv-logs-swift",
    platforms: [
        .macOS(.v13),
        .iOS(.v15),
    ],
    // The only product is the library. The conformance runners below are
    // executable targets, not products: `swift run --package-path
    // packages/logs-swift conformance-runner` still builds and runs them in
    // this (root) package, but a dependent package cannot see them.
    products: [
        .library(name: "EvolveLogs", targets: ["EvolveLogs"]),
    ],
    targets: [
        .target(
            name: "EvolveLogsC",
            path: "Sources/EvolveLogsC",
            linkerSettings: [
                // gzip bodies (Transport.gzip → Gzip.c over the system zlib).
                .linkedLibrary("z"),
            ]
        ),
        .target(
            name: "EvolveLogs",
            dependencies: ["EvolveLogsC"],
            path: "Sources/EvolveLogs"
        ),
        .executableTarget(
            name: "conformance-runner",
            dependencies: ["EvolveLogs"],
            path: "Sources/conformance-runner"
        ),
        .executableTarget(
            name: "flags-conformance-runner",
            dependencies: ["EvolveLogs"],
            path: "Sources/flags-conformance-runner"
        ),
        .testTarget(
            name: "EvolveLogsTests",
            dependencies: ["EvolveLogs", "EvolveLogsC"],
            path: "Tests/EvolveLogsTests",
            resources: [
                // Shared context-fitting/fingerprint vectors, generated by
                // packages/flags-client/scripts/write-vectors.ts and kept
                // byte-identical by packages/flags-client/__tests__/vectors.spec.ts.
                .copy("Resources/vectors.json"),
            ]
        ),
    ]
)
